production:
  solr:
    hostname: localhost
    port: 3000
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 3000
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 3000
    log_level: WARNING